spring.application.name=open-finance-hub
server.port=8085

spring.data.mongodb.uri=mongodb://mongodb:27017/open_finance_hub

spring.data.mongodb.auto-index-creation=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}